accounts/urls.py
from django.urls import path
from . import views
from newapp import views as newappviews

app_name = "accounts"


urlpatterns = [
     path('',views.LoginPage , name='login'),
    path('login/',views.LoginPage , name='login'),
    path('signup/',views.registration_view, name='signup'),
    path('custom_login/',views.LoginPage, name='custom_login'),
    path('logout/',views.LogoutPage, name='logout'),

    

]

elearning_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('newapp/', include('newapp.urls')),
    path('', include('accounts.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newapp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name  = 'newapp'


urlpatterns = [
    path('home/',views.home , name='home'),
    path('givetest/<int:category_id>',views.givetest ,name = 'givetest'),
    path('add_category/', views.add_category , name = 'add_category'),
    path('add_test/', views.add_test , name= 'add_test'),

    path('add_question/', views.add_question, name='add_question'),
    path('add_question/<int:categories>/', views.add_question, name='add_question'),
    path('test_category_filter/', views.test_category_filter, name='test_category_filter'),
    path('add_article/', views.add_article, name='add_article'),
    path('forum/', views.forum, name='forum'),
    path('all_article/', views.all_article, name='all_article'),

    path('forum/', views.forum, name='forum'),





    

]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newapp/models.py
from django.db import models
from django.conf import settings

from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
        return self.name


class test(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Question(models.Model):
    OPTION_CHOICES = (
        ('option1', 'Option One'),
        ('option2', 'Option Two'),
        ('option3', 'Option Three'),
        ('option4', 'Option Four'),
    )

    category = models.ForeignKey(test, on_delete=models.CASCADE)
    question = models.CharField(max_length=300)
    option1 = models.CharField(max_length=100)
    option2 = models.CharField(max_length=100)
    option3 = models.CharField(max_length=100)
    option4 = models.CharField(max_length=100)
    correct_answer = models.CharField(max_length=8, choices=OPTION_CHOICES)


    def __str__(self):
        return self.question

class Article(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    file = models.FileField(upload_to='article_files/')
 # Define the upload_to directory

    def __str__(self):
        return self.title
    
from django.conf import settings
from django.db import models

class fquestion(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.TextField()

    def __str__(self):
        return self.text

class Answer(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    question = models.ForeignKey(fquestion, on_delete=models.CASCADE)
    text = models.TextField()

newapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse 
from .models import test, Question, Category ,Article , fquestion, Answer
from django.contrib.auth.decorators import login_required
from .decorators import student_required, teacher_required
# Create your views here.
@login_required(login_url='/login/')

def home(request):
    # if request.user.user_type == 'teacher
    print(request.user.is_authenticated)
    category = Category.objects.all()
    test_set = test.objects.all() 
    print(request.user.user_type)
    

    context = {
        'category': category,
        'test': test_set
        }
    if request.user.user_type == 'teacher':
        return render(request, 'teacher.html',context)
    elif request.user.user_type == 'student':
        return render(request, 'student.html',context)
    else:
        return HttpResponse('You need to be a teacher or a student')

@login_required(login_url='/login/')
@student_required
def givetest(request, category_id):
    category = get_object_or_404(test, id=category_id)
    allquestions = Question.objects.filter(category=category)
    total_questions = allquestions.count()

        # Add question_number field to each question
    for idx, question in enumerate(allquestions, start=1):
        question.question_number = idx
    if request.method == 'POST':
        
        score = 0
        corrected_answer = 0
        incorrect_answer = 0
        not_answered= 0
        ques_no = 0

        for question in allquestions:
            submitted_answer = request.POST.get(f'q{question.id}')
            correct_answer = question.correct_answer

            if submitted_answer == correct_answer:
                score += 1
                corrected_answer+=1
            elif submitted_answer is None:
                not_answered+=1
            
            else:
                incorrect_answer += 1

        # Calculate the percentage score
        percentage_score = (score / total_questions) * 100

        # You can pass the score or percentage_score to the template as needed
        # For example:
        return render(request, 'results.html', {
            'category': category,
            'total_questions': total_questions,
            'score': score,
            'percentage_score': percentage_score,
            'correct_answers': corrected_answer,
            'incorrect_answers': incorrect_answer,
            'not_answered' : not_answered,
            'ques_no': ques_no,
        })

    return render(request, 'give_test.html', {'category': category, 'allquestions': allquestions ,'total_questions': total_questions} )


@login_required(login_url='/login/')
@teacher_required
def add_question(request):
    if request.method == 'POST':
            
            # If the "Add another question" button is clicked, save the current question data
            category_id = request.POST.get('category')
            category = test.objects.get(pk=category_id)
            question = request.POST.get('question')
            option1 = request.POST.get('option1')
            option2 = request.POST.get('option2')
            option3 = request.POST.get('option3')
            option4 = request.POST.get('option4')
            correct_answer = request.POST.get('correct_answer')
            if not category_id or not question or not option1 or not option2 or not option3 or not option4 or not correct_answer:
            # If any field is missing, display an error message or handle the situation accordingly

                return HttpResponse("Enter every field")



            question_obj = Question(category=category, question=question, option1=option1, option2=option2, option3=option3, option4=option4, correct_answer=correct_answer)
            print(question_obj)
            question_obj.save()
  
            # Redirect back to the same page to add another question
            if 'submit' in request.POST:
                return redirect('newapp:home')
            elif 'another_question' in request.POST:
                return redirect('newapp:add_question')

    else:
        categories = test.objects.all()
        return render(request, 'add_question.html', {'categories': categories})



def test_category_filter(request):
    if request.method == 'POST':
        selected_category_id = request.POST.get('selected_category')
        print(selected_category_id)
        all_category = Category.objects.all()
        if selected_category_id:
            selected_tests = test.objects.filter(category=selected_category_id)
            # Redirect to the 'givetest' view with the selected category ID
            context = {'selected_tests': selected_tests
                       ,'all_category': all_category}
            return render(request , 'test_category_filter.html', context)
        else:
            # If no category is selected, redirect back to the same page
            return redirect('newapp:home')

    else:
        # If it's a GET request, fetch all categories from the database
        test_set = test.objects.all()
        categories = Category.objects.all()
        
        # Fetch all tests if no category is selected or filter the tests by the selected category
        
        return render(request, 'test_category_filter.html', {'categories': categories, 'test_set': test_set})
    

@login_required(login_url='/login/')
@teacher_required
def add_category(request):
    if request.method == 'POST':
        category = request.POST.get('category')
    
        new_category = Category(name=category)
        print(new_category)
        new_category.save()

        if 'submit' in request.POST:
            print("yes submit button pressed")
            return redirect('newapp:home')
        elif 'another_category' in request.POST:
            print("no submit button pressed")
            return redirect('newapp:add_category')
    return render(request, 'add_category.html')
        


@login_required(login_url='/login/')
@teacher_required     
def add_test(request):
    if request.method == 'POST':
        test_name = request.POST.get('test_name')
        category_id = request.POST.get('category')
        
        if not test_name or not category_id:
            # If the test_name or category is missing, display an error message or handle the situation accordingly
            return HttpResponse("Please enter the test name and select a category.")
        
        # Get the selected category object
        category = get_object_or_404(Category, id=category_id)
        
        # Save the new test with the selected category
        new_test = test(name=test_name, category=category)
        new_test.save()
        
        # Redirect to the home page or any other appropriate page
        return redirect('newapp:home')

    categories = Category.objects.all()
    return render(request, 'add_test.html', {'categories': categories})



@login_required(login_url='/login/')
@teacher_required   
def add_article(request):
    if request.method == 'POST':
        # Get form data from the request
        if request.method == 'POST':
            print("yes post request")
        title = request.POST['title']
        content = request.POST['content']
        file = request.FILES['file']

        # Create the article with the user reference
        user = request.user 
        print(user)
         # The logged-in user
        article = Article.objects.create(user=user, title=title, content=content, file=file)
        print(article)
        article.save()


        return redirect('newapp:home')  # Redirect to the articles list page
    else:
        print("get request done")
        return render(request, 'add_article.html')


def all_article(request):
    # Fetch all articles from the database
    articles = Article.objects.all()
    print(articles)
    
    # Pass the list of articles to the template context
    context = {'articles': articles}
    
    return render(request, 'all_article.html', context)



def article(request):
    if request.method == 'GET':
        context = {
            'article' : Article
        }
        
        return render(request, 'article.html', context)
    
 
    
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import fquestion, Answer

@login_required
def forum(request):
    if request.method == 'POST':
        if 'question_text' in request.POST:
            # Handle submitted question
            question_text = request.POST.get('question_text')
            fquestion.objects.create(user=request.user, text=question_text)
        elif 'answer_text' in request.POST:
            # Handle submitted answer
            question_id = request.POST.get('question_id')
            text = request.POST.get('answer_text')
            question = fquestion.objects.get(pk=question_id)
            Answer.objects.create(user=request.user, question=question, text=text)
        
        return redirect('newapp:forum')  # Redirect to prevent form resubmission

    questions = fquestion.objects.all().order_by('-id')
    context = {'questions': questions}
    return render(request, 'forum.html', context)

newapp/templates/add_article.html
{% extends 'base.html' %}

{% block  test %}

<div class="container mt-5">
    <h1>Upload Article</h1>
    <form enctype="multipart/form-data" method="POST"%}">
      {% csrf_token %}
      <div class="mb-3">
        <label for="title" class="form-label">Article Title</label>
        <input type="text" class="form-control" id="title" name="title" required>
      </div>
      <div class="mb-3">
        <label for="content" class="form-label">Article Content</label>
        <textarea class="form-control" id="content" name="content" rows="5" required></textarea>
      </div>
      <div class="mb-3">
        <label for="file" class="form-label">Upload Article File</label>
        <input type="file" class="form-control" id="file" name="file" accept=".pdf, .doc, .docx" required>
      </div>
      <button type="submit" class="btn btn-primary">Upload Article</button>
    </form>
  </div>

{% endblock test  %}

newapp/templates/add_category.html
{% extends 'base.html' %}

{% block test %}

<form method="POST">
    {% csrf_token %}

<div class="form-floating dark-bg text-light">
    <input type="text" class="form-control dark-text" id="category" name="category" >
    <label for="option1">Category</label>
</div>


<button name="submit"  type="submit" class="btn btn-warning  shadow rounded-2 ">submit</button>
<button  type="text"  name ="another_category" class="btn btn-warning  shadow rounded-2 ">Add another category </button>
</form>
{% endblock test %}

newapp/templates/add_question.html
{% extends 'base.html' %}

{% block test %}

<form method="POST">
    {% csrf_token %}
<div class="form-floating mb-3 dark-bg text-light">
        <select class="form-control dark-text" name="category" id="category" arial-lebel="Select Category">
            <option value="" disabled selected>Select an option</option>
            
            {% for category in categories %}
                <option value="{{ category.id }}">{{ category.name }}</option>
            {% endfor %}
        </select>
        <label for="category">Choose a Topic</label>
</div>  


<div class="form-floating mb-3 dark-bg text-light">
    <input type="text" class="form-control dark-text" id="question" name = "question" >
    <label for="question">Type the Question Here </label>
</div>
<div class="form-floating dark-bg text-light">
    <input type="text" class="form-control dark-text" id="option1" name="option1" >
    <label for="option1">Option1</label>
</div>
<div class="form-floating dark-bg text-light">
    <input type="text" class="form-control dark-text" id="option2" name="option2" >
    <label for="option2">Option2</label>
</div>
<div class="form-floating dark-bg text-light">
    <input type="text" class="form-control dark-text" id="option3" name="option3" >
    <label for="option3">Option3</label>
</div>
<div class="form-floating dark-bg text-light">
    <input type="text" class="form-control dark-text" id="option4" name="option4">
    <label for="option4">Option4</label>
</div>
<div class="form-floating dark-bg text-light">
    <select class="form-control dark-text" id="correct_answer" name="correct_answer">
        <option value="" disabled selected>Choose The Answer</option>
        <option value="option1">Option One</option>
        <option value="option2">Option Two</option>
        <option value="option3">Option Three</option>
        <option value="option4">Option Four</option>
    </select>
    <label for="correct_answer">Correct Answer</label>
</div>


<button  type="submit" class="btn btn-warning  shadow rounded-2" name="submit">submit</button>
<button  type="text"  name ="another_question" class="btn btn-warning  shadow rounded-2 ">Add another question </button>
</form>
{% endblock test %}

newapp/templates/add_test.html
{% extends 'base.html' %}
  
<!-- Main content goes here -->
{% block test %}
<br>
<div class="container mt-4">
    <h2 class="text">Add New Test</h2>
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label class="text" for="test_name">Test Name</label>
            <input type="text" class="form-control" id="test_name" name="test_name" required>
        </div>
        <div class="form-group">
            <label class="text" for="category">Category</label>
            <select class="form-control" id="category" name="category" required>
                <option value="" disabled selected>Select an option</option>
                {% for category in categories %}
                    <option value="{{ category.id }}">{{ category.name }}</option>
                {% endfor %}
            </select>
        </div>
        <!-- You can add more form fields here for other test-related data if needed -->
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>


{% endblock test %}

newapp/templates/all_article.html
{% extends 'base.html' %}

{% block test %}

<div class="container mt-5">
    <h1 class="btn btn-danger">Uploaded Articles</h1>
    <div class="row row-cols-1 row-cols-md-4 g-4">
        {% for article in articles %}
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ article.title }}</h5>
                        <p class="card-text">{{ article.content }}</p>
                        <a href="{{ article.file.url }}" class="btn btn-primary">Download Article</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock test %}

newapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SmartEd Connect</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body id="body">


    <nav class="navbar navbar-expand-lg bg-warning ">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarTogglerDemo01">

            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'newapp:home' %}">Quiz</a>
              </li>

              <li>
                <a class="nav-link" href="{% url 'newapp:forum' %}">Student Forum</a>
  
                </li>
                <li>
                  <a class="nav-link" href="{% url 'newapp:all_article' %}">Article</a>
    
                  </li>
                  <li>
                    <a class="nav-link" href="{% url 'accounts:logout' %}">LogOut</a>
      
                    </li>

            </ul>

          </div>
        </div>
      </nav>




{% block test %}
{% endblock test %}



    
    <footer id="footer" class="bg-dark text-light text-center py-3" style="margin-top: 100%;">
        <!-- Footer content -->
        &copy; SmartEd Connect. All rights reserved.
    </footer>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

newapp/templates/forum.html
{% extends 'base.html' %}

{% block test %}
    <div class="container mt-5">
        <h1 class= "btn btn-danger d-flex justify-content-center ">Welcome to the Forum</h1>

        <div class="row mt-4 border border-white">
            <div class="col-md-6">
                <h2 class="btn btn-secondary mt-2">Ask a Question</h2>
                <form method="post" action="{% url 'newapp:forum' %}" class="mb-4">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="font-weight-bold text-light" for="question_text ">Question:</label>
                        <input type="text" class="form-control" name="question_text" required>
                    </div>
                    <button type="submit" class="btn btn-primary mt-2">Submit</button>
                </form>
            </div>
        </div>

        <h2 class="mt-4 btn btn-success d-flex justify-content-center">Questions and Answers</h2>
        {% for question in questions %}
            <div class="card mb-4">
                <div class="card-body">
                    <div class="border border-black p-1 mb-2">
                        <h5 class="card-title text-info">{{ question.text }}</h5>
                        <p class="card-subtitle mb-2 text-muted">Posted by: {{ question.user.username }}</p>   
                    </div>

                    <h6 class="card-subtitle mb-2 font-weight-bold text-danger">Answers:</h6>
                    <ul class="list-unstyled">
                        {% for answer in question.answer_set.all %}
                            <li>
                                {{ answer.text }} </br>
                                <span class="text-muted"> - by {{ answer.user.username }}</span>
                            </li>
                            <hr class="bg-danger">
                           
                        {% endfor %}
                        
                    </ul>
                    <form method="post" action="{% url 'newapp:forum' %}">
                        {% csrf_token %}
                        <input type="hidden" name="question_id" value="{{ question.id }}">
                        <div class="form-group">
                            <label for="answer_text">Your Answer:</label>
                            <input type="text" class="form-control" name="answer_text" required>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit Answer</button>
                    </form>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock test %}

newapp/templates/results.html
{% extends 'base.html' %}
{% block test %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title text-center mb-4">Quiz Results</h2>
                    <div class="result-item">
                        <h5 class="mb-3">Total Questions:</h5>
                        <p>{{ total_questions }}</p>
                    </div>
                    <div class="result-item">
                        <h5 class="mb-3">Correct Answers:</h5>
                        <p>{{ correct_answers }}</p>
                    </div>
                    <div class="result-item">
                        <h5 class="mb-3">Not Answered:</h5>
                        <p>{{ not_answered }}</p>
                    </div>
                    <div class="result-item">
                        <h5 class="mb-3">Incorrect Answers:</h5>
                        <p>{{ incorrect_answers }}</p>
                    </div>
                    <div class="result-item">
                        <h5 class="mb-3">Score:</h5>
                        <p>{{ percentage_score }}%</p>
                    </div>
                    <div class="text-center mt-4">
                        <a href="{% url 'newapp:home' %}" class="btn btn-primary">Back to Home</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock test %}

newapp/templates/student.html
{% extends 'base.html' %}
  
<!-- Main content goes here -->
{% block test %}
<br>


<h2 id="h2" class="text-center">Choose the Category you want to give test.</h2>



<section class="w-75 mx-auto my-5">
  <form method="POST" action="{% url 'newapp:test_category_filter' %}">
    {% csrf_token %}
    <select name="selected_category" class="form-select" aria-label="Select Category">
      <option value="">All Categories</option>
      {% for categoryy in category %}
        <option value="{{ categoryy.id }}">{{ categoryy.name }}</option>
      {% endfor %}
    </select>
    <button type="submit" class="btn btn-primary mt-3">Filter</button>
  </form>
</section>



<ul class="list-group w-75 mx-auto mt-1">
  {% for tst in test %}
  <p class="d-inline-flex gap-1 ">
      <button class="btn btn-secondary button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample{{ tst.id }}" aria-expanded="false" aria-controls="collapseExample{{ tst.id }}">
          <li class="list-group-item button" text-decoration-none text-dark>{{ tst.name }}</li>
      </button>
  </p>
  <div class="collapse " id="collapseExample{{ tst.id }}">
      <div class="card card-body button afterclick">
          <li class="list-group-item"><a href="{% url 'newapp:givetest' tst.id %}" class="text-decoration-none text-dark">Start Exam</a></li>
      </div>
  </div>
  {% endfor %}
</ul>







{% endblock test %}

newapp/templates/teacher.html
{% extends 'base.html' %}
  
<!-- Main content goes here -->
{% block test %}
<br>

<div class="col-4">
  <!-- Step 1: Add Category -->
  <p class="text-secondary ">Step 1: Begin by adding a new category to organize your tests.</p>
  <a href="{% url 'newapp:add_category' %}"><button type="button" class="btn btn-danger m-2 ">Add Category</button></a>

  <!-- Step 2: Add Test -->
  <p class="text-secondary ">Step 2: Create tests under relevant categories to challenge your learners.</p>
  <a href="{% url 'newapp:add_test' %}"><button type="button" class="btn btn-danger m-2">Add Test</button></a>

  <!-- Step 3: Add Questions -->
  <p class="text-secondary ">Step 3: Craft questions for your tests to assess knowledge and skills.</p>
  <a href="{% url 'newapp:add_question' %}"><button type="button" class="btn btn-danger m-2 ">Add Questions</button></a>
</div>



<h1 class="text-secondary text-success ">Add article</h1>
<a href="{% url 'newapp:add_article' %}"><button type="button" class="btn btn-success m-2 ">Add Article</button></a>


{% endblock test %}

newapp/templates/test_category_filter.html
{% extends 'base.html' %}
  
<!-- Main content goes here -->
{% block test %}
<br>


<h2 id="h2" class ="text-center mx-5">Choose the test you want to take.</h2>


<section class="w-75 mx-auto">
<form method="POST" action="{% url 'newapp:test_category_filter'  %}">
    {% csrf_token %}
  <select name="selected_category" class="form-select" aria-label="Select Category">
    <option value="">All Categories</option>
    {% for categoryy in all_category %}
      <option value="{{ categoryy.id }}">{{ categoryy.name }}</option>
    {% endfor %}
  </select>
  <button type="submit" class="btn btn-primary filter mt-3 ">Filter</button>
</form>
</section>




<ul class="list-group w-75 mx-auto mt-3">
    {% for tst in selected_tests %}
    <p class="d-inline-flex gap-1 ">
        <button class="btn btn-secondary button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample{{ tst.id }}" aria-expanded="false" aria-controls="collapseExample{{ tst.id }}">
            <li class="list-group-item button" text-decoration-none text-dark>{{ tst.name }}</li>
        </button>
    </p>
    <div class="collapse " id="collapseExample{{ tst.id }}">
        <div class="card card-body button afterclick">
            <li class="list-group-item"><a href="{% url 'newapp:givetest' tst.id %}" class="text-decoration-none text-dark">Start Exam</a></li>
        </div>
    </div>
    {% endfor %}
  </ul>
  
  



{% endblock test %}

newapp/templates/tests.html
{% extends 'base.html' %}

<!-- Main content goes here -->
{% block test %}
<br>

<div class="col-4">
  <a href="{% url 'newapp:add_test' %}"><button type="button" class="btn btn-danger m-2">Add Test</button></a>
  <a href="{% url 'newapp:add_category' %}"><button type="button" class="btn btn-danger m-2">Add Category</button></a>
  <a href="{% url 'newapp:add_question' %}"><button type="button" class="btn btn-danger m-2">Add Questions</button></a>
</div>

<!-- Step 1: Choose a Category -->
<h2 id="h2">Step 1: Choose the Category you want to give a test.</h2>

<section>
  <form method="POST" action="{% url 'newapp:test_category_filter' %}">
    {% csrf_token %}
    <p>Select a category to filter tests:</p>
    <select name="selected_category" class="form-select" aria-label="Select Category">
      <option value="">All Categories</option>
      {% for categoryy in category %}
        <option value="{{ categoryy.id }}">{{ categoryy.name }}</option>
      {% endfor %}
    </select>
    <button type="submit" class="btn btn-primary">Filter</button>
  </form>
</section>

<!-- Step 2: Available Tests -->
<h2>Step 2: Available Tests</h2>

<ul class="list-group">
  {% for tst in test %}
  <p class="d-inline-flex gap-1">
    <button class="btn btn-secondary button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample{{ tst.id }}" aria-expanded="false" aria-controls="collapseExample{{ tst.id }}">
      <li class="list-group-item button" text-decoration-none text-dark">{{ tst.name }} (Click to Expand)</li>
    </button>
  </p>
  <div class="collapse" id="collapseExample{{ tst.id }}">
    <div class="card card-body button afterclick">
      <!-- Step 3: Start Exam -->
      <p>Step 3: Start the Exam</p>
      <li class="list-group-item"><a href="{% url 'newapp:givetest' tst.id %}" class="text-decoration-none text-dark">Start Exam</a></li>
    </div>
  </div>
  {% endfor %}
</ul>

{% endblock test %}